### ISSUE TITLE
Why do you limit iOS version?

### ISSUE THREAD

**Issue by hot-wolf** [HKUST-Aerial-Robotics/VINS-Mobile#77]
I test VINS on iphone6s both iOS10 and iOS9, I found it's fluency on iOS10 but it's lagging on iOS9, is it owing to the dependency of ceres solver?

**Comment by PeiliangLi** [comment]
Hi, it's because we only fully test it on iOS 10.2.1 and above. And we are not very professional in apple development, so we don't know the detail difference between different iOS versions. For excluding the system level factors which we don't understand, we suggest users run it on iOS 10.2.1 and above.

**Comment by hot-wolf** [comment]
thank you for your response!
